pipeline {
  agent any
    
  tools {nodejs "node"}
    
  stages {
        
    stage('Git') {
      steps {
        git 'hpipeline {
  agent any
    
  tools {nodejs "node"}
    
  stages {
        
    stage('Git') {
      steps {
        git 'https://github.com/basavarajbhavi/shopping-cart.git'
      }
    }
     
    stage('Build') {
      steps {
        powershell 'npm install'
         powershell '<<Build Command>>'
      }
    }  
    
            
    stage('Test') {
      steps {
        powershell 'node test'
      }
    }
  }
}t'
      }
    }
     
    stage('Build') {
      steps {
        powershell 'npm install'
         powershell '<<Build Command>>'
      }
    }  
    
            
    stage('Test') {
      steps {
        powershell 'node test'
      }
    }
  }
}
